apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaUser
metadata:
  namespace: %NAMESPACE%
  labels:
    app: eem-demo-apis
    app.kubernetes.io/component: eem-demo-apis
    app.kubernetes.io/instance: eem-demo-apis
    app.kubernetes.io/part-of: eem-demo-apis
    eventstreams.ibm.com/cluster: %ES_CLUSTER%
  name: %ES_CLUSTER%--eem-user
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: "*"
        operation: Read
        resource:
          name: "*"
          patternType: literal
          type: group
      - host: "*"
        operation: All
        resource:
          name: "*"
          patternType: literal
          type: topic
    type: simple